require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
-- require "user.cmp"
require "user.blink"
require "user.conform"
require "user.linting"
require "user.markdown"
require "user.treesitter"
require "user.nvimtree"
require "user.telescope"
require "user.gitsigns"
require "user.lualine"
require "user.autopairs"
require "user.languagetool"
require "user.zen-mode"
require "user.telekasten"
require "user.gitlab"
require "user.indent-line"
require "user.lsp"
require "user.lsp.dap"
require("user.lsp.neotest")
require "user.codecompanion"
